### ISSUE TITLE
Validation in edit category

### ISSUE THREAD

**Issue by VladislavPetyukevich** [sorface/interview-platform#109]
Come up with a verification algorithm when editing a category

**Comment by blowin** [comment]
It is necessary to improve the algorithm of assigning a parent when editing a category. If you want to assign one of Child as Parent for a category, you should forbid such behavior.

Improve the search for potential categories to be assigned as parent. It is necessary to pass the id of the category being edited to the frontend, and the backend in turn does not need to return all its child categories.
