### ISSUE TITLE
Personal questions

### ISSUE THREAD

**Issue by VladislavPetyukevich** [sorface/interview-platform#31]
- All users can create questions, but this questions is personal. Only admins have rights to create public questions.
- User can view public questions and only own personal questions in questions list (`GET /api/questions`).
- All users in room can see somebody personal questions if this question in room questions list (`GET /api/room-questions`).

`POST /api/room-questions` should create personal questions

**Comment by blowin** [comment]
Discussion. Based on the discussion, RoomId should be removed from Question and also add the question type Public/Private as a new field.
